create table kualitaslagu (
	id_lagu VARCHAR(50),
	kualitas_audio TEXT
);
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG31502', 'quis lectus');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG27463', 'id lobortis');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG42760', 'blandit ultrices enim');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG84315', 'eleifend donec');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG92165', 'risus');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG44244', 'volutpat dui');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG12944', 'et ultrices posuere');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG94212', 'amet diam');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG38205', 'quam sapien');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG19441', 'sed accumsan');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG69400', 'sapien sapien non');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG34762', 'vel lectus in');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG20433', 'amet consectetuer');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG45883', 'nonummy maecenas');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG25051', 'primis in');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG54874', 'curae');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG71808', 'quisque');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG17697', 'id ligula');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG21494', 'at velit vivamus');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG38530', 'parturient montes nascetur');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG56426', 'turpis');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG42077', 'potenti nullam');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG57578', 'lectus pellentesque');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG53408', 'bibendum morbi non');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG91024', 'nulla eget eros');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG72558', 'ipsum primis in');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG28453', 'ultrices');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG26961', 'ante vel ipsum');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG96983', 'posuere metus vitae');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG02644', 'rhoncus mauris enim');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG62355', 'libero');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG50737', 'proin interdum mauris');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG22323', 'mauris non ligula');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG00476', 'eget massa tempor');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG86790', 'cursus id');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG75758', 'nisl nunc nisl');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG04860', 'lorem integer tincidunt');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG57435', 'volutpat');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG07426', 'sit amet justo');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG45673', 'sit amet');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG17938', 'tincidunt eu');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG98369', 'condimentum curabitur');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG33605', 'sed ante');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG64509', 'lacinia nisi venenatis');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG07260', 'ligula nec');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG15203', 'proin');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG58185', 'nunc');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG49780', 'eu');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG99635', 'lacus curabitur');
insert into kualitaslagu (id_lagu, kualitas_audio) values ('SNG56522', 'volutpat');
