create table lirik (
	id_lagu VARCHAR(8),
	baris INT,
	email_penulis VARCHAR(50),
	lirik_lagu TEXT,
    FOREIGN KEY (id_lagu) REFERENCES lagu(id_lagu),
    FOREIGN KEY (email_penulis) REFERENCES appleid(email)
);

insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG53017', 60, 'avaughng@dagondesign.com', 'implement turn-key supply-chains');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG37007', 39, 'jburnsall7@phpbb.com', 'envisioneer scalable solutions');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG55826', 70, 'jburnsall7@phpbb.com', 'synergize user-centric technologies');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG87383', 34, 'nluffman0@theglobeandmail.com', 'maximize efficient e-business');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG67179', 1, 'wromanf@ihg.com', 'expedite wireless mindshare');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG09675', 57, 'wromanf@ihg.com', 'architect sticky niches');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG74486', 47, 'jlyptrade6@google.it', 'innovate user-centric e-services');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG64130', 41, 'jlyptrade6@google.it', 'visualize front-end supply-chains');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG28146', 13, 'nluffman0@theglobeandmail.com', 'maximize bleeding-edge portals');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG56432', 1, 'wromanf@ihg.com', 'scale viral functionalities');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG04277', 58, 'jlyptrade6@google.it', 'deliver holistic niches');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG31111', 69, 'lpaudind@abc.net.au', 'visualize efficient systems');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG70463', 30, 'nluffman0@theglobeandmail.com', 'revolutionize user-centric experiences');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG87383', 10, 'lpaudind@abc.net.au', 'incubate cutting-edge systems');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG33609', 84, 'nliston3@ihg.com', 'empower sexy synergies');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG25566', 10, 'lmerigonb@admin.ch', 'utilize user-centric infomediaries');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG11591', 11, 'nluffman0@theglobeandmail.com', 'facilitate web-enabled ROI');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG74486', 85, 'avaughng@dagondesign.com', 'iterate virtual technologies');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG44306', 80, 'wromanf@ihg.com', 'unleash rich niches');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG92779', 97, 'wromanf@ihg.com', 'revolutionize 24/365 synergies');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG56662', 94, 'wromanf@ihg.com', 'integrate impactful markets');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG13197', 90, 'avaughng@dagondesign.com', 'revolutionize global e-commerce');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG15400', 44, 'jburnsall7@phpbb.com', 'orchestrate cross-platform e-business');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG99950', 82, 'nluffman0@theglobeandmail.com', 'e-enable magnetic paradigms');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG66853', 52, 'wromanf@ihg.com', 'innovate one-to-one technologies');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG63620', 2, 'clarvente@adobe.com', 'monetize customized bandwidth');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG85255', 96, 'nliston3@ihg.com', 'e-enable efficient deliverables');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG59261', 67, 'nliston3@ihg.com', 'extend virtual architectures');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG42416', 100, 'lpaudind@abc.net.au', 'harness killer ROI');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG24040', 87, 'lmerigonb@admin.ch', 'redefine strategic interfaces');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG56662', 53, 'nluffman0@theglobeandmail.com', 'cultivate leading-edge web services');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG30250', 34, 'clarvente@adobe.com', 'target killer channels');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG76833', 23, 'nliston3@ihg.com', 'seize mission-critical deliverables');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG21308', 61, 'clarvente@adobe.com', 'maximize next-generation networks');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG92539', 57, 'jlyptrade6@google.it', 'productize sticky niches');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG62530', 96, 'nliston3@ihg.com', 'visualize 24/7 web-readiness');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG64130', 33, 'clarvente@adobe.com', 'redefine wireless portals');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG67179', 73, 'lpaudind@abc.net.au', 'generate frictionless functionalities');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG33169', 13, 'lmerigonb@admin.ch', 'integrate revolutionary convergence');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG02891', 49, 'avaughng@dagondesign.com', 'utilize collaborative niches');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG63620', 69, 'wromanf@ihg.com', 'innovate revolutionary markets');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG66853', 78, 'nluffman0@theglobeandmail.com', 'target B2B web services');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG37466', 41, 'lpaudind@abc.net.au', 'scale impactful web services');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG47766', 61, 'avaughng@dagondesign.com', 'harness visionary niches');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG04059', 44, 'lpaudind@abc.net.au', 'synergize killer networks');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG78850', 53, 'avaughng@dagondesign.com', 'expedite user-centric bandwidth');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG21308', 94, 'lpaudind@abc.net.au', 'exploit cutting-edge synergies');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG23463', 4, 'nluffman0@theglobeandmail.com', 'morph back-end infrastructures');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG43799', 24, 'wromanf@ihg.com', 'engineer scalable e-tailers');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG31416', 76, 'nliston3@ihg.com', 'enhance integrated mindshare');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG10287', 5, 'lmerigonb@admin.ch', 'envisioneer frictionless content');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG70783', 1, 'nliston3@ihg.com', 'whiteboard B2B systems');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG27716', 4, 'wromanf@ihg.com', 'evolve front-end platforms');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG46648', 81, 'clarvente@adobe.com', 'revolutionize proactive schemas');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG97996', 17, 'wromanf@ihg.com', 'visualize vertical vortals');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG54061', 28, 'wromanf@ihg.com', 'deliver B2C infomediaries');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG47766', 5, 'nluffman0@theglobeandmail.com', 'utilize bleeding-edge systems');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG99365', 64, 'lmerigonb@admin.ch', 'enhance collaborative niches');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG37466', 15, 'nluffman0@theglobeandmail.com', 'incubate B2C web services');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG46619', 22, 'nliston3@ihg.com', 'seize viral portals');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG04059', 38, 'avaughng@dagondesign.com', 'harness proactive synergies');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG04886', 40, 'clarvente@adobe.com', 'utilize end-to-end deliverables');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG11591', 48, 'lpaudind@abc.net.au', 'reintermediate robust paradigms');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG37007', 65, 'avaughng@dagondesign.com', 'scale e-business architectures');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG05651', 72, 'avaughng@dagondesign.com', 'synthesize best-of-breed e-markets');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG47766', 92, 'nluffman0@theglobeandmail.com', 'revolutionize open-source paradigms');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG78850', 6, 'nluffman0@theglobeandmail.com', 'visualize out-of-the-box initiatives');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG24271', 35, 'lpaudind@abc.net.au', 'innovate B2C content');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG93594', 43, 'lmerigonb@admin.ch', 'repurpose global paradigms');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG23725', 49, 'wromanf@ihg.com', 'envisioneer cross-media schemas');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG63985', 63, 'jburnsall7@phpbb.com', 'evolve dot-com models');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG33609', 29, 'lpaudind@abc.net.au', 'engineer sexy experiences');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG31108', 100, 'lpaudind@abc.net.au', 'cultivate strategic technologies');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG70783', 52, 'wromanf@ihg.com', 'engineer cutting-edge e-markets');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG70463', 15, 'wromanf@ihg.com', 'matrix wireless e-services');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG37007', 95, 'nluffman0@theglobeandmail.com', 'deploy vertical metrics');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG63985', 72, 'nluffman0@theglobeandmail.com', 'utilize extensible systems');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG87383', 68, 'wromanf@ihg.com', 'extend bricks-and-clicks web-readiness');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG59261', 17, 'clarvente@adobe.com', 'whiteboard extensible paradigms');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG11591', 76, 'jburnsall7@phpbb.com', 'transition collaborative experiences');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG25320', 17, 'wromanf@ihg.com', 'mesh bricks-and-clicks niches');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG04277', 12, 'avaughng@dagondesign.com', 'integrate B2C technologies');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG79564', 69, 'jlyptrade6@google.it', 'evolve end-to-end schemas');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG11686', 56, 'jburnsall7@phpbb.com', 'benchmark robust infrastructures');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG47766', 34, 'avaughng@dagondesign.com', 'engineer mission-critical networks');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG43576', 17, 'jburnsall7@phpbb.com', 'transition dot-com initiatives');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG31111', 88, 'lmerigonb@admin.ch', 'facilitate integrated solutions');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG14032', 100, 'clarvente@adobe.com', 'utilize scalable networks');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG13197', 46, 'lmerigonb@admin.ch', 'strategize 24/7 schemas');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG11686', 27, 'jburnsall7@phpbb.com', 'utilize impactful experiences');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG99365', 8, 'lmerigonb@admin.ch', 'visualize distributed eyeballs');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG37466', 6, 'clarvente@adobe.com', 'extend magnetic web services');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG78850', 78, 'lpaudind@abc.net.au', 'leverage seamless e-commerce');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG76924', 69, 'clarvente@adobe.com', 'architect viral e-markets');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG74486', 93, 'nluffman0@theglobeandmail.com', 'transform sticky experiences');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG25505', 100, 'wromanf@ihg.com', 'evolve leading-edge relationships');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG33609', 58, 'lpaudind@abc.net.au', 'harness clicks-and-mortar infomediaries');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG87383', 61, 'wromanf@ihg.com', 'empower interactive initiatives');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG04277', 18, 'jlyptrade6@google.it', 'visualize seamless content');
insert into liriklagu (id_lagu, baris, email_penulis, lirik_lagu) values ('SNG54061', 94, 'jburnsall7@phpbb.com', 'revolutionize cutting-edge solutions');
